reporter:
  - text
  - text-summary
  - html
  - lcov
extension:
  - .ts
require:
  - ts-node/register
  - source-map-support/register
exclude:
  - '**/*.spec.ts'
  - build/**/*
  - test/**/*
sourceMap: true
instrument: true
