/** These must never change */
const enum ActionId {
  CombatActivatePrayers = 1,
  CombatCastSpellStd = 2,
  CombatCastSpellAncient = 3,
  CombatCastSpellArchaic = 4,
  CombatCastSpellAurora = 5,
  CombatCastSpellCurse = 6,
  CombatSetAttackStyle = 7,
  CombatStartCombatStd = 8,
  CombatStartCombatSlayer = 9,
  CombatStartCombatDungeon = 10,
  CoreBuyItem = 11,
  CoreDelay = 12,
  CoreEquipFood = 13,
  CoreEquipItem = 14,
  CoreSellItem = 15,
  WorkflowSetStepIdx = 16,
  CoreSwitchEquipmentSets = 17,
  CoreUsePotion = 18,
  StartSkillAgility = 19,
  StartSkillAltMagic = 20,
  StartSkillAstrology = 21,
  StartSkillCooking = 22,
  StartSkillCrafting = 23,
  StartSkillFiremaking = 24,
  StartSkillFishing = 25,
  StartSkillFletching = 26,
  StartSkillHerblore = 27,
  StartSkillMining = 28,
  StartSkillRunecrafting = 29,
  StartSkillSmithing = 30,
  StartSkillSummoning = 31,
  StartSkillThieving = 32,
  StartSkillWoodcutting = 33,
  WorkflowExecWorkflow = 34,
  WorkflowExecEmbeddedWorkflow = 35,
  CoreLoadAgilityBlueprint = 36,
}

export default ActionId;
