inputs:
  node-version:
    description: Node version
    required: true
name: Cache
description: Cache TSC & ESLint
runs:
  using: composite
  steps:
    - name: Make TSC cache key
      shell: bash
      run: cat package-lock.json | grep rollup-plugin-typescript2 > .ci-cache-key
    - name: Typescript cache
      uses: actions/cache@v3
      with:
        path: "./node_modules/.cache/rollup-plugin-typescript2"
        key: v1-tsc-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('./.ci-cache-key') }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          v1-tsc-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('./.ci-cache-key') }}-${{ github.ref }}-
          v1-tsc-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('./.ci-cache-key') }}-refs/heads/master-
          v1-tsc-${{ runner.os }}-${{ inputs.node-version }}-${{ hashFiles('./.ci-cache-key') }}-
          v1-tsc-${{ runner.os }}-${{ inputs.node-version }}-
          v1-tsc-${{ runner.os }}
    - name: Clean TSC cache key temp file
      shell: bash
      run: rm .ci-cache-key
    - name: ESLint cache
      uses: actions/cache@v3
      with:
        path: "./node_modules/.cache/eslint"
        key: v1-eslint-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          v1-eslint-${{ github.ref }}-
          v1-eslint-refs/heads/master-
