name: Feature Request
description: I want a thing
labels: ["feature request"]
body:
  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What best describes your request?
      options:
        - A new action
        - A new trigger
#        - Additions to the mod API
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What are you missing?
    validations:
      required: true
  - type: checkboxes
    id: TOS
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you confirm that the requested feature fits the [contribution guidelines](/Alorel/melvor-action-workflows/blob/master/.github/CONTRIBUTING.md#what-belongs-and-doesnt-belong-in-the-main-mod) & agree to follow the [code of conduct](/Alorel/melvor-action-workflows/blob/master/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow the code of conduct
          required: true
        - label: My request fits the contribution guidelines
          required: true
        - label: I have searched for similar issues and nothing similar exists
          required: true
