name: Release
on:
  release:
    types:
      - created

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        name: Get changelog
        id: get-body
        with:
          result-encoding: string
          script: return context.payload.release.body;
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-node@v3
        name: Set up Node
        with:
          node-version: 18
          cache: npm
          registry-url: https://npm.pkg.github.com
      - name: NPM install
        run: npm ci --no-fund
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: npm run lint
      - run: npm run rollup:prod
        name: Build
        env:
          MELVOR_MOD_VERSION: ${{ github.ref_name }}
      - run: npm run modio -- upload --active --token "${{ secrets.MOD_IO_API_TOKEN }}" --mod-version "${{ github.ref_name }}" --changelog ${{ steps.get-body.outputs.result }}
        name: Publish
